{
  "openapi": "3.1.0",
  "info": {
    "title": "payments",
    "version": "1.0.2"
  },
  "servers": [
    {
      "url": "https://api-sandbox.y.uno/v1"
    }
  ],
  "components": {
    "securitySchemes": {
      "sec0": {
        "type": "apiKey",
        "in": "header",
        "x-default": "<Your public-api-key>",
        "name": "public-api-key"
      },
      "sec1": {
        "type": "apiKey",
        "in": "header",
        "name": "private-secret-key",
        "x-default": "<Your private-secret-key>"
      }
    }
  },
  "security": [
    {
      "sec0": [],
      "sec1": []
    }
  ],
  "paths": {
    "/payments/{payment_id}": {
      "get": {
        "summary": "Retrieve Payment by ID",
        "description": "",
        "operationId": "retrieve-payment-by-id-v2",
        "parameters": [
          {
            "name": "raw_response",
            "in": "query",
            "description": "When true, includes the provider raw response in the output (default false).",
            "schema": {
              "type": "boolean"
            }
          },
          {
            "name": "transactions_history",
            "in": "query",
            "description": "When true, includes the transactions history in the response (default false).",
            "schema": {
              "type": "boolean"
            }
          },
          {
            "in": "path",
            "name": "payment_id",
            "schema": {
              "type": "string"
            },
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "200",
            "content": {
              "application/json": {
                "examples": {
                  "Full payment object": {
                    "value": {
                      "payment": {
                        "account_code": "25f3a410-1e77-4e98-afcd-ed8acfd19b15",
                        "account_id": "25f3a410-1e77-4e98-afcd-ed8acfd19b15",
                        "additional_data": {
                          "airline": null,
                          "order": null,
                          "seller_details": null,
                          "transportations": null
                        },
                        "amount": {
                          "captured": 0,
                          "currency": "USD",
                          "currency_conversion": null,
                          "refunded": 0,
                          "value": 1
                        },
                        "callback_url": "https://epicvin.com/check-vin-number-and-get-the-vehicle-history-report/checkout/2fmpk3j94lba39390",
                        "checkout": {
                          "sdk_action_required": true,
                          "session": "45bfff61-6cb2-45b7-994f-8b71beb28ea4"
                        },
                        "country": "US",
                        "created_at": "2026-06-09T16:22:07.170427Z",
                        "customer_payer": {
                          "billing_address": {
                            "address_line_1": "N*A",
                            "address_line_2": "",
                            "city": "N/A",
                            "country": "DE",
                            "neighborhood": null,
                            "state": "N/A",
                            "zip_code": "1***1"
                          },
                          "browser_info": {
                            "accept_browser": "selenide-test",
                            "accept_content": "text/html",
                            "accept_header": "text/html",
                            "browser_time_difference": "0",
                            "color_depth": "24",
                            "java_enabled": false,
                            "javascript_enabled": true,
                            "language": "en-US",
                            "platform": "WEB",
                            "screen_height": "600",
                            "screen_width": "800",
                            "user_agent": "selenide-test"
                          },
                          "date_of_birth": null,
                          "device_fingerprint": "45bfff61-6cb2-45b7-994f-8b71beb28ea4",
                          "device_fingerprints": [
                            {
                              "id": "45bfff61-6cb2-45b7-994f-8b71beb28ea4",
                              "provider_id": "AIRWALLEX"
                            },
                            {
                              "id": "",
                              "provider_id": "STRIPE"
                            }
                          ],
                          "document": null,
                          "email": "epi*********t+8@epicvin.com",
                          "first_name": "T**t",
                          "gender": "",
                          "geolocation": {
                            "latitude": "51.165691",
                            "longitude": "10.451526"
                          },
                          "id": "84052948-4da6-41c6-ab2b-279f7ae5e2ae",
                          "ip_address": "148.251.127.208",
                          "last_name": "",
                          "merchant_customer_created_at": "2023-10-04T12:39:47.000Z",
                          "merchant_customer_id": "534933",
                          "merchant_customer_validations": {
                            "account_is_verified": true,
                            "email_is_verified": true,
                            "phone_is_verified": true
                          },
                          "nationality": null,
                          "phone": null,
                          "shipping_address": {
                            "address_line_1": "",
                            "address_line_2": "",
                            "neighborhood": null
                          }
                        },
                        "description": "FULL HISTORY UNLIM",
                        "fraud_screening": null,
                        "id": "29cc6030-3921-4f48-a302-18abb95ebad5",
                        "idempotency_key": "55792bd3-9642-4732-8c09-4f533b7a81dc",
                        "merchant_order_id": "45874e2d43201c88bdfad2a599b31d9e",
                        "metadata": [
                          {
                            "key": "indicator",
                            "value": "INITIAL"
                          },
                          {
                            "key": "sub_type",
                            "value": "trial"
                          },
                          {
                            "key": "sub_id",
                            "value": "subs_mLO4kMdr66V7HiH5SxE7u4Vu"
                          }
                        ],
                        "payment_link_code": "",
                        "routing_rules": {
                          "condition": {
                            "description": "",
                            "id": 316815,
                            "name": "3ds_test"
                          },
                          "monitors": false,
                          "smart_routing": false
                        },
                        "split_marketplace": [],
                        "status": "DECLINED",
                        "sub_status": "DECLINED",
                        "taxes": null,
                        "transactions": [
                          {
                            "amount": 1,
                            "category": "CARD",
                            "connection_data": {
                              "id": "defd3143-eced-4ab1-a73e-1bbcd66d8fd7",
                              "name": "3ds"
                            },
                            "created_at": "2026-06-09T16:22:07.283548Z",
                            "description": "FULL HISTORY UNLIM",
                            "id": "45bfff61-6cb2-45b7-994f-8b71beb28ea4",
                            "merchant_advice_code": null,
                            "merchant_advice_code_message": null,
                            "merchant_reference": "45874e2d43201c88bdfad2a599b31d9e",
                            "payment_method": {
                              "detail": {
                                "card": {
                                  "authorization_code": "",
                                  "capture": false,
                                  "card_data": {
                                    "brand": "VISA",
                                    "category": "TRADITIONAL",
                                    "country_code": "US",
                                    "expiration_month": "*",
                                    "expiration_year": "**",
                                    "fingerprint": "bbe080f4-3208-4552-97ad-bc2ba61c5688",
                                    "holder_name": "T**T",
                                    "iin": "40000000",
                                    "issuer_code": null,
                                    "issuer_name": "INTL HDQTRSCENTER OWNED",
                                    "lfd": "3220",
                                    "number_length": 16,
                                    "scheme": "VISA",
                                    "security_code_length": 3,
                                    "three_d_secure": {
                                      "acs_id": "e59e4767-5520-4a70-8239-9912a936bc1e",
                                      "cryptogram": "eyJhY3NUcmFuc0lEIjoiZTU5ZTQ3NjctNTUyMC00YTcwLTgyMzktOTkxMmE5MzZiYzFlIiwiY2hhbGxlbmdlV2luZG93U2l6ZSI6IjA1IiwibWVzc2FnZVR5cGUiOiJDUmVxIiwibWVzc2FnZVZlcnNpb24iOiIyLjMuMSIsInRocmVlRFNTZXJ2ZXJUcmFuc0lEIjoiNDdmZmRiMWEtMDdiNC00MzQ0LThmODQtZTRhMWI5NjY1MzZiIn0",
                                      "directory_server_transaction_id": "db203a55-6627-46f6-a8d3-48eeb9833ca1",
                                      "electronic_commerce_indicator": "01",
                                      "pares_status": "N",
                                      "transaction_id": "47ffdb1a-07b4-4344-8f84-e4a1b966536b",
                                      "version": "2.3.1"
                                    },
                                    "type": "CREDIT"
                                  },
                                  "first_installment_deferral": 0,
                                  "installment_amount": null,
                                  "installments": 1,
                                  "installments_plan_id": null,
                                  "installments_total_amount": null,
                                  "installments_type": "",
                                  "retrieval_reference_number": "",
                                  "soft_descriptor": "",
                                  "stored_credentials": {
                                    "network_transaction_id": null,
                                    "reason": "SUBSCRIPTION",
                                    "subscription_agreement_id": "subs_mLO4kMdr66V7HiH5SxE7u4Vu",
                                    "usage": "FIRST"
                                  },
                                  "verify": false,
                                  "voucher": null
                                }
                              },
                              "otp": {
                                "retries": {}
                              },
                              "parent_payment_method_type": null,
                              "token": "2c7f191**********************18ae715",
                              "type": "CARD",
                              "vault_on_success": false,
                              "vaulted_token": ""
                            },
                            "provider_data": {
                              "account_id": "",
                              "id": "NETCETERA_3DS",
                              "iso8583_response_code": null,
                              "iso8583_response_message": null,
                              "merchant_advice_code": null,
                              "merchant_advice_code_message": null,
                              "raw_response": "[REDACTED]",
                              "reason_code": null,
                              "reason_description": null,
                              "response_code": null,
                              "response_message": null,
                              "status": "N",
                              "status_detail": "",
                              "sub_status": "",
                              "third_party_account_id": null,
                              "third_party_transaction_id": null,
                              "transaction_id": "47ffdb1a-07b4-4344-8f84-e4a1b966536b"
                            },
                            "provider_id": "NETCETERA_3DS",
                            "reason": null,
                            "response_code": "CHALLENGE_CANCELED",
                            "response_message": "The challenge was canceled",
                            "split_marketplace": [],
                            "status": "DECLINED",
                            "type": "THREE_D_SECURE",
                            "updated_at": "2026-06-09T16:22:14.987039Z"
                          }
                        ],
                        "updated_at": "2026-06-09T16:22:15.014265Z",
                        "workflow": "SDK_CHECKOUT"
                      }
                    }
                  }
                },
                "schema": {
                  "type": "object",
                  "properties": {
                    "payment": {
                      "type": "object",
                      "properties": {
                        "id": { "type": "string", "example": "29cc6030-3921-4f48-a302-18abb95ebad5" },
                        "account_id": { "type": "string", "example": "25f3a410-1e77-4e98-afcd-ed8acfd19b15" },
                        "account_code": { "type": "string", "example": "25f3a410-1e77-4e98-afcd-ed8acfd19b15" },
                        "description": { "type": "string", "example": "FULL HISTORY UNLIM" },
                        "country": { "type": "string", "example": "US" },
                        "status": { "type": "string", "example": "DECLINED" },
                        "sub_status": { "type": "string", "example": "DECLINED" },
                        "merchant_order_id": { "type": "string", "example": "45874e2d43201c88bdfad2a599b31d9e" },
                        "idempotency_key": { "type": "string", "example": "55792bd3-9642-4732-8c09-4f533b7a81dc" },
                        "payment_link_code": { "type": "string", "example": "" },
                        "created_at": { "type": "string", "example": "2026-06-09T16:22:07.170427Z" },
                        "updated_at": { "type": "string", "example": "2026-06-09T16:22:15.014265Z" },
                        "workflow": { "type": "string", "example": "SDK_CHECKOUT" },
                        "taxes": { "type": "object", "example": null, "nullable": true },
                        "callback_url": { "type": "string", "example": "https://epicvin.com/check-vin-number-and-get-the-vehicle-history-report/checkout/2fmpk3j94lba39390" },
                        "amount": {
                          "type": "object",
                          "properties": {
                            "value": { "type": "integer", "example": 1 },
                            "currency": { "type": "string", "example": "USD" },
                            "captured": { "type": "integer", "example": 0 },
                            "refunded": { "type": "integer", "example": 0 },
                            "currency_conversion": { "type": "object", "example": null, "nullable": true }
                          }
                        },
                        "checkout": {
                          "type": "object",
                          "properties": {
                            "session": { "type": "string", "example": "45bfff61-6cb2-45b7-994f-8b71beb28ea4" },
                            "sdk_action_required": { "type": "boolean", "example": true }
                          }
                        },
                        "additional_data": {
                          "type": "object",
                          "properties": {
                            "airline": { "type": "object", "example": null, "nullable": true },
                            "order": { "type": "object", "example": null, "nullable": true },
                            "seller_details": { "type": "object", "example": null, "nullable": true },
                            "transportations": { "type": "array", "example": null, "nullable": true }
                          }
                        },
                        "fraud_screening": { "type": "object", "example": null, "nullable": true },
                        "routing_rules": {
                          "type": "object",
                          "properties": {
                            "condition": {
                              "type": "object",
                              "properties": {
                                "id": { "type": "integer", "example": 316815 },
                                "name": { "type": "string", "example": "3ds_test" },
                                "description": { "type": "string", "example": "" }
                              }
                            },
                            "monitors": { "type": "boolean", "example": false },
                            "smart_routing": { "type": "boolean", "example": false }
                          }
                        },
                        "split_marketplace": { "type": "array" },
                        "metadata": {
                          "type": "array",
                          "items": {
                            "type": "object",
                            "properties": {
                              "key": { "type": "string", "example": "indicator" },
                              "value": { "type": "string", "example": "INITIAL" }
                            }
                          }
                        },
                        "customer_payer": {
                          "type": "object",
                          "properties": {
                            "id": { "type": "string", "example": "84052948-4da6-41c6-ab2b-279f7ae5e2ae" },
                            "merchant_customer_id": { "type": "string", "example": "534933" },
                            "merchant_customer_created_at": { "type": "string", "example": "2023-10-04T12:39:47.000Z" },
                            "first_name": { "type": "string", "example": "Test" },
                            "last_name": { "type": "string", "example": "" },
                            "gender": { "type": "string", "example": "" },
                            "date_of_birth": { "type": "string", "example": null, "nullable": true },
                            "email": { "type": "string", "example": "epictest@epicvin.com" },
                            "document": { "type": "object", "example": null, "nullable": true },
                            "phone": { "type": "object", "example": null, "nullable": true },
                            "nationality": { "type": "string", "example": null, "nullable": true },
                            "ip_address": { "type": "string", "example": "148.251.127.208" },
                            "device_fingerprint": { "type": "string", "example": "45bfff61-6cb2-45b7-994f-8b71beb28ea4" },
                            "device_fingerprints": {
                              "type": "array",
                              "items": {
                                "type": "object",
                                "properties": {
                                  "id": { "type": "string", "example": "45bfff61-6cb2-45b7-994f-8b71beb28ea4" },
                                  "provider_id": { "type": "string", "example": "AIRWALLEX" }
                                }
                              }
                            },
                            "geolocation": {
                              "type": "object",
                              "properties": {
                                "latitude": { "type": "string", "example": "51.165691" },
                                "longitude": { "type": "string", "example": "10.451526" }
                              }
                            },
                            "merchant_customer_validations": {
                              "type": "object",
                              "properties": {
                                "account_is_verified": { "type": "boolean", "example": true },
                                "email_is_verified": { "type": "boolean", "example": true },
                                "phone_is_verified": { "type": "boolean", "example": true }
                              }
                            },
                            "browser_info": {
                              "type": "object",
                              "properties": {
                                "accept_header": { "type": "string", "example": "text/html" },
                                "user_agent": { "type": "string", "example": "selenide-test" },
                                "language": { "type": "string", "example": "en-US" },
                                "screen_height": { "type": "string", "example": "600" },
                                "screen_width": { "type": "string", "example": "800" },
                                "color_depth": { "type": "string", "example": "24" },
                                "java_enabled": { "type": "boolean", "example": false },
                                "javascript_enabled": { "type": "boolean", "example": true },
                                "browser_time_difference": { "type": "string", "example": "0" },
                                "platform": { "type": "string", "example": "WEB" }
                              }
                            },
                            "billing_address": {
                              "type": "object",
                              "properties": {
                                "address_line_1": { "type": "string", "example": "N/A" },
                                "address_line_2": { "type": "string", "example": "" },
                                "city": { "type": "string", "example": "N/A" },
                                "state": { "type": "string", "example": "N/A" },
                                "country": { "type": "string", "example": "DE" },
                                "zip_code": { "type": "string", "example": "10111" },
                                "neighborhood": { "type": "string", "example": null, "nullable": true }
                              }
                            },
                            "shipping_address": {
                              "type": "object",
                              "properties": {
                                "address_line_1": { "type": "string", "example": "" },
                                "address_line_2": { "type": "string", "example": "" },
                                "neighborhood": { "type": "string", "example": null, "nullable": true }
                              }
                            }
                          }
                        },
                        "transactions": {
                          "type": "array",
                          "items": {
                            "type": "object",
                            "properties": {
                              "id": { "type": "string", "example": "45bfff61-6cb2-45b7-994f-8b71beb28ea4" },
                              "type": { "type": "string", "example": "THREE_D_SECURE" },
                              "category": { "type": "string", "example": "CARD" },
                              "status": { "type": "string", "example": "DECLINED" },
                              "amount": { "type": "number", "example": 1 },
                              "description": { "type": "string", "example": "FULL HISTORY UNLIM" },
                              "merchant_reference": { "type": "string", "example": "45874e2d43201c88bdfad2a599b31d9e" },
                              "reason": { "type": "string", "example": null, "nullable": true },
                              "response_code": { "type": "string", "example": "CHALLENGE_CANCELED" },
                              "response_message": { "type": "string", "example": "The challenge was canceled" },
                              "merchant_advice_code": { "type": "string", "example": null, "nullable": true },
                              "merchant_advice_code_message": { "type": "string", "example": null, "nullable": true },
                              "created_at": { "type": "string", "example": "2026-06-09T16:22:07.283548Z" },
                              "updated_at": { "type": "string", "example": "2026-06-09T16:22:14.987039Z" },
                              "provider_id": { "type": "string", "example": "NETCETERA_3DS" },
                              "connection_data": {
                                "type": "object",
                                "properties": {
                                  "id": { "type": "string", "example": "defd3143-eced-4ab1-a73e-1bbcd66d8fd7" },
                                  "name": { "type": "string", "example": "3ds" }
                                }
                              },
                              "split_marketplace": { "type": "array" },
                              "payment_method": {
                                "type": "object",
                                "properties": {
                                  "type": { "type": "string", "example": "CARD" },
                                  "token": { "type": "string", "example": "2c7f191...18ae715" },
                                  "vaulted_token": { "type": "string", "example": "" },
                                  "vault_on_success": { "type": "boolean", "example": false },
                                  "parent_payment_method_type": { "type": "string", "example": null, "nullable": true },
                                  "detail": {
                                    "type": "object",
                                    "properties": {
                                      "card": {
                                        "type": "object",
                                        "properties": {
                                          "authorization_code": { "type": "string", "example": "" },
                                          "capture": { "type": "boolean", "example": false },
                                          "installments": { "type": "integer", "example": 1 },
                                          "installments_type": { "type": "string", "example": "" },
                                          "installments_plan_id": { "type": "string", "example": null, "nullable": true },
                                          "installment_amount": { "type": "number", "example": null, "nullable": true },
                                          "installments_total_amount": { "type": "number", "example": null, "nullable": true },
                                          "first_installment_deferral": { "type": "integer", "example": 0 },
                                          "retrieval_reference_number": { "type": "string", "example": "" },
                                          "soft_descriptor": { "type": "string", "example": "" },
                                          "verify": { "type": "boolean", "example": false },
                                          "voucher": { "type": "object", "example": null, "nullable": true },
                                          "card_data": {
                                            "type": "object",
                                            "properties": {
                                              "brand": { "type": "string", "example": "VISA" },
                                              "type": { "type": "string", "example": "CREDIT" },
                                              "category": { "type": "string", "example": "TRADITIONAL" },
                                              "country_code": { "type": "string", "example": "US" },
                                              "scheme": { "type": "string", "example": "VISA" },
                                              "iin": { "type": "string", "example": "40000000" },
                                              "lfd": { "type": "string", "example": "3220" },
                                              "number_length": { "type": "integer", "example": 16 },
                                              "security_code_length": { "type": "integer", "example": 3 },
                                              "expiration_month": { "type": "string", "example": "*" },
                                              "expiration_year": { "type": "string", "example": "**" },
                                              "holder_name": { "type": "string", "example": "T**T" },
                                              "fingerprint": { "type": "string", "example": "bbe080f4-3208-4552-97ad-bc2ba61c5688" },
                                              "issuer_name": { "type": "string", "example": "INTL HDQTRSCENTER OWNED" },
                                              "issuer_code": { "type": "string", "example": null, "nullable": true },
                                              "three_d_secure": {
                                                "type": "object",
                                                "properties": {
                                                  "version": { "type": "string", "example": "2.3.1" },
                                                  "electronic_commerce_indicator": { "type": "string", "example": "01" },
                                                  "transaction_id": { "type": "string", "example": "47ffdb1a-07b4-4344-8f84-e4a1b966536b" },
                                                  "directory_server_transaction_id": { "type": "string", "example": "db203a55-6627-46f6-a8d3-48eeb9833ca1" },
                                                  "acs_id": { "type": "string", "example": "e59e4767-5520-4a70-8239-9912a936bc1e" },
                                                  "pares_status": { "type": "string", "example": "N" },
                                                  "cryptogram": { "type": "string", "example": "eyJhY3NUcmFuc0lE..." }
                                                }
                                              }
                                            }
                                          },
                                          "stored_credentials": {
                                            "type": "object",
                                            "properties": {
                                              "network_transaction_id": { "type": "string", "example": null, "nullable": true },
                                              "reason": { "type": "string", "example": "SUBSCRIPTION" },
                                              "subscription_agreement_id": { "type": "string", "example": "subs_mLO4kMdr66V7HiH5SxE7u4Vu" },
                                              "usage": { "type": "string", "example": "FIRST" }
                                            }
                                          }
                                        }
                                      }
                                    }
                                  },
                                  "otp": {
                                    "type": "object",
                                    "properties": {
                                      "retries": { "type": "object" }
                                    }
                                  }
                                }
                              },
                              "provider_data": {
                                "type": "object",
                                "properties": {
                                  "id": { "type": "string", "example": "NETCETERA_3DS" },
                                  "account_id": { "type": "string", "example": "" },
                                  "status": { "type": "string", "example": "N" },
                                  "status_detail": { "type": "string", "example": "" },
                                  "sub_status": { "type": "string", "example": "" },
                                  "response_code": { "type": "string", "example": null, "nullable": true },
                                  "response_message": { "type": "string", "example": null, "nullable": true },
                                  "reason_code": { "type": "string", "example": null, "nullable": true },
                                  "reason_description": { "type": "string", "example": null, "nullable": true },
                                  "merchant_advice_code": { "type": "string", "example": null, "nullable": true },
                                  "merchant_advice_code_message": { "type": "string", "example": null, "nullable": true },
                                  "iso8583_response_code": { "type": "string", "example": null, "nullable": true },
                                  "iso8583_response_message": { "type": "string", "example": null, "nullable": true },
                                  "third_party_account_id": { "type": "string", "example": null, "nullable": true },
                                  "third_party_transaction_id": { "type": "string", "example": null, "nullable": true },
                                  "transaction_id": { "type": "string", "example": "47ffdb1a-07b4-4344-8f84-e4a1b966536b" },
                                  "raw_response": { "type": "string", "example": "[REDACTED]" }
                                }
                              }
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "400",
            "content": {
              "application/json": {
                "examples": {
                  "Bad request": {
                    "value": {
                      "code": "INVALID_REQUEST",
                      "messages": [
                        "Invalid request"
                      ]
                    }
                  }
                },
                "schema": {
                  "type": "object",
                  "properties": {
                    "code": {
                      "type": "string",
                      "example": "INVALID_REQUEST"
                    },
                    "messages": {
                      "type": "array",
                      "items": {
                        "type": "string",
                        "example": "Invalid request"
                      }
                    }
                  }
                }
              }
            }
          },
          "401": {
            "description": "401",
            "content": {
              "application/json": {
                "examples": {
                  "Unauthorized": {
                    "value": {
                      "code": "INVALID_CREDENTIALS",
                      "messages": [
                        "Invalid Credentials"
                      ]
                    }
                  }
                },
                "schema": {
                  "type": "object",
                  "properties": {
                    "code": {
                      "type": "string",
                      "example": "INVALID_CREDENTIALS"
                    },
                    "messages": {
                      "type": "array",
                      "items": {
                        "type": "string",
                        "example": "Invalid Credentials"
                      }
                    }
                  }
                }
              }
            }
          },
          "403": {
            "description": "403",
            "content": {
              "application/json": {
                "examples": {
                  "Forbidden": {
                    "value": {
                      "code": "AUTHORIZATION_REQUIRED",
                      "messages": [
                        "The merchant has no authorization to use this API"
                      ]
                    }
                  }
                },
                "schema": {
                  "type": "object",
                  "properties": {
                    "code": {
                      "type": "string",
                      "example": "AUTHORIZATION_REQUIRED"
                    },
                    "messages": {
                      "type": "array",
                      "items": {
                        "type": "string",
                        "example": "The merchant has no authorization to use this API"
                      }
                    }
                  }
                }
              }
            }
          }
        },
        "deprecated": false
      }
    }
  },
  "x-readme": {
    "headers": [
      {
        "key": "charset",
        "value": "utf-8"
      }
    ],
    "explorer-enabled": true,
    "proxy-enabled": true
  }
}
